### ISSUE TITLE
Доработки

### ISSUE THREAD

**Issue by alexkoss** [manteei/Row_grouping#1]
Мария, добрый день!
Александр, Уно-софт
На большом файле не работает:

```
PS D:\git\TESTEN\java\Row_grouping\target> java -jar .\row_grouping-1.0-SNAPSHOT.jar d:\test\lng-big.csv           
2024-08-13 09:25:29 INFO  App - Reading the file d:\test\lng-big.csv
2024-08-13 09:25:30 INFO  FileManager - File processed
2024-08-13 09:25:30 ERROR App - There is no correct data in the file or it is empty
2024-08-13 09:25:30 INFO  App - Program completed, running time: 1 seconds
```

**Comment by manteei** [comment]
Добрый день, этот код для файла из тестового. Для большого файла пришлось немного менять метод чтения с файла, т. к. он отличается по структуре . Сделать код универсальным для обоих файлов?

**Comment by manteei** [comment]
> Мария, добрый день! Александр, Уно-софт На большом файле не работает:
> 
> ```
> PS D:\git\TESTEN\java\Row_grouping\target> java -jar .\row_grouping-1.0-SNAPSHOT.jar d:\test\lng-big.csv           
> 2024-08-13 09:25:29 INFO  App - Reading the file d:\test\lng-big.csv
> 2024-08-13 09:25:30 INFO  FileManager - File processed
> 2024-08-13 09:25:30 ERROR App - There is no correct data in the file or it is empty
> 2024-08-13 09:25:30 INFO  App - Program completed, running time: 1 seconds
> ```

Добрый день, этот код для файла из тестового. Для большого файла пришлось немного менять метод чтения с файла, т. к. он отличается по структуре . Сделать код универсальным для обоих файлов?

**Comment by alexkoss** [comment]
@manteei, да

**Comment by manteei** [comment]
@alexkoss , добавила
